chore(readme): 리드미 업데이트 -1
minhyeok0328/next-loop pull request #94
Opened 2024-11-28 08:11 UTC by imella0707

리드미 업데이트했습니다. 
branch 이름을 91-issue 로 정했습니다. 
수정할 내역 있으면 알려주세요 !

2024-11-28 08:14 UTC, minhyeok0328 approved these changes

2024-11-28 08:14 UTC, minhyeok0328 commented on chore(readme): 파이프라인 이미지 업데이트-2
이거 파일명을 README.md로 바꿔야 repository 방문할 때 보입니다!
파일명이 잘못되었네요

2024-11-28 08:15 UTC, imella0707 commented on chore(readme): 파이프라인 이미지 업데이트-2
아 어쩐지 안보여서, 다시바꾸겠습니다 ! 일단 내용을 좀 써봤는데 수정할 부분 있으면 알려주세용 ~

2024-11-28 08:22 UTC, minhyeok0328 approved these changes

2024-11-28 08:22 UTC, minhyeok0328 commented on README.md
> +  - 리전: 서울 (asia-northeast3-a)
asia-northeast3-a
뒤에 -a 빼야 합니당
a 영역만 쓰는게 아니니까여

2024-11-28 08:22 UTC, minhyeok0328 commented on README.md
> +- 데이터 파이프라인은 4개의 주요 계층으로 구성되어 있음.<br>
계층 > 단계로 단어 바꿔야 할 것 같아요
계층은 적절하지는 않은 단어 같습니다

2024-11-28 08:22 UTC, minhyeok0328 commented on README.md
> +  - GCS(Google Cloud Storage)에 직접 데이터를 저장하거나, GCS에서 데이터 가져오는 것도 가능.
`GCS(Google Cloud Storage)에 직접 데이터를 저장하거나, GCS에서 데이터 가져오는 것도 가능.`
이게 저희 파이프라인 역할 및 각 단계에서 어떻게 동작하는지 설명하는데
데이터 가져오는 것도 가능이라고 쓰면 GCS 기능 설명하는 것 같아서 조금 어색해 보입니당

2024-11-28 08:23 UTC, imella0707 commented on README.md
> +  - 리전: 서울 (asia-northeast3-a)
오 네넵 삭제하겠습니다.

2024-11-28 08:24 UTC, imella0707 commented on README.md
> +- 데이터 파이프라인은 4개의 주요 계층으로 구성되어 있음.<br>
저도 단계가 더 적절한 단어인 거 같습니다. 다시 보니까 어색한 게 보이네요 !

2024-11-28 08:41 UTC, imella0707 commented on README.md
> +  - GCS(Google Cloud Storage)에 직접 데이터를 저장하거나, GCS에서 데이터 가져오는 것도 가능.
넵. 'GCS에서 데이터 가져오는 것도 가능' 이 부분 삭제하고,  다시 보니, '저장소' → '저장'으로 수정하고 싶어서 일단 그렇게 업데이트 해보겠습니다 ~!

2024-11-29 01:58 UTC, dnlpys requested changes

2024-11-29 01:58 UTC, dnlpys commented on README.md
> +      - Staging: 테스트 중인 모델.
실험 조건에 맞는 상위 n개 모델. << 이 표현이 더 좋아보여요.

2024-11-29 01:58 UTC, dnlpys commented on README.md
> +      - Archived: Porduction에 있던 과거 모델은 archived로 변경, 더 이상 사용되지 않는 모델.
더 이상 사용하진 않는다는 표현은 적절하지 못해보입니다. 새로 배포된 모델의 성능에 문제가 있을 경우, 롤백해서 다시 사용해야될 경우가 있을수 있습니다.

archived로 변경. 까지만 쓰는것이 적절해 보입니다.

2024-11-29 01:58 UTC, dnlpys commented on README.md
> +- Logstash나 Telegraf같은 Pushing 방식보다 모니터링 서버에 영향이 가는 장애가 적은 편이어서 모니터링 도구로 선택하게 되었음.
👍

2024-11-29 05:57 UTC, imella0707 commented on README.md
> +      - Staging: 테스트 중인 모델.
네 조금 더 구체적으로 서술해주는 게  좋을 거 같네요. 감사합니다 !

2024-11-29 06:11 UTC, imella0707 commented on README.md
> +      - Archived: Porduction에 있던 과거 모델은 archived로 변경, 더 이상 사용되지 않는 모델.
네 롤백해야될 경우가 있으니까 더이상 사용하지 않는다고 단정지으면 안 될 것 같아요. 감사합니다 ~

2024-12-02 01:47 UTC, dnlpys approved these changes
LGTM👍👍👍

2024-12-02 05:32 UTC, merged